version: '3'

services:

  mock-server:
    container_name: mock_server
    build: ./mock_server
    ports:
      - 8002:8002
    networks:
      - orb-network

  orb:
    container_name: orb
    build: ./orb
    links:
      - mock-server
    ports:
      - 8001:8001
    networks:
      - orb-network

networks:
  orb-network:
    driver: bridge
