BASE_URL = 'http://localhost:8000'
IRISES_PATH = 'orb/irises/'

SIGNUP_URL = BASE_URL + '/signup'
REPORT_STATUS_URL = BASE_URL + '/status'

STATUS_REPORT_INTERVAL = 3  # secs
LIFE_EVENT_INTERVAL = 5  # secs

TEMP_DELTA = 1
BATTERY_UPDATE_DELTA = -2
CPU_USAGE_DELTA = 2
DISK_SPACE_DELTA = -2
